sudo: required
language: java
jdk:
  - openjdk15
services:
  - docker
after_success:
  - docker-compose build
  - docker-compose up -d
  - travis_wait 10
  - docker-compose down
 - bash <(curl -s https://codecov.io/bash) -t 5fc4669d-1a7b-4ead-bb1a-b075763266f6