# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: .
    ports:
      - "2904:2904"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: therecanbeonlyone
    ports:
        - "3306:3306"
    volumes:
        - "./initdb:/docker-entrypoint-initdb.d/:rw"